010 : Create project structure
ledukilian/LeduKilian_P3_18012021 pull request #12
Opened 2021-01-25 05:52 UTC by ledukilian

close #10

2021-01-25 12:26 UTC, Tutt-J requested changes
Please use Bootstrap CDN and put css files on assets folder

2021-01-25 12:26 UTC, Tutt-J commented on index.html
> +            <meta name="description" content="Maquette du projet 3 Openclassrooms">
Please put a real description

2021-01-25 12:26 UTC, Tutt-J commented on index.html
> +            <meta name="keywords" content="Maquette, Projet, Openclassrooms">
Please put reals keywords

2021-01-25 20:21 UTC, ledukilian commented
close #10

2021-01-26 10:34 UTC, Tutt-J requested changes
Please remove all class

2021-02-02 08:29 UTC, Tutt-J approved these changes

2021-02-02 08:30 UTC, merged